### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by wwjje** [vimaec/public#1]
Startup error，Why is this?
![图片](https://github.com/vimaec/public/assets/39489205/1bd45a17-a4b9-4eb1-b1ba-156a9b3d5f86)
log-Application：
2023-11-23 16:09:31.228 +08:00 [INF] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-11-23 16:09:31.233 +08:00 [INF] Application Started (v1.2.81 - public (#da1b5b) 2023-09-05)
2023-11-23 16:09:31.278 +08:00 [INF] Assembly version: 1.2.81.0
2023-11-23 16:09:31.278 +08:00 [INF] Commit Hash: da1b5b49f8e42a9ba7e0f1aa6d3284e3ad89bf40
2023-11-23 16:09:31.278 +08:00 [INF] Working Directory: C:\Program Files\VIM\VIM Desktop
2023-11-23 16:09:31.280 +08:00 [INF] args: "C:\Program Files\VIM\VIM Desktop\VIM.dll"
2023-11-23 16:09:31.281 +08:00 [INF] options:
StartupFilePath: 
DeploymentTarget: Production
OOBE: False
DisablePlugins: False
EnableDevenv: False
DownloadDirectory: 
StorageUriOverride: 
Log: 
NoSplash: False
SimulateRendererInitializationFailure: False
2023-11-23 16:09:31.376 +08:00 [ERR] Fatal Exception
System.IO.FileNotFoundException: Could not load file or assembly 'clrWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
File name: 'clrWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Vim.Desktop.App.RegisterTypes(IContainerRegistry containerRegistry)
   at Prism.PrismApplicationBase.Initialize()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by wwjje** [comment]
![图片](https://github.com/vimaec/public/assets/39489205/da123830-ca8f-4dd1-9276-c05ac4c35f9d)
The clrWrapper file exists
